### ISSUE TITLE
How do I add another "desktop" with the scripts?

### ISSUE THREAD

**Issue by kimusan** [bmullan/CIAB_Remote_Desktop_System-v6#6]
I have had the system running with an Ubuntu desktop, and it has been running great for some time now. I however needed it to be updated from the Ubuntu 20.04 to the 21.04 version, but after upgrade I just get a black screen (or failing connection from sessman) when trying to access the desktop. 
This is not a problem, as I can basically just spin up a new desktop and throw away the old one (though it would be nice to figure out why it does not work).

Is there a way to use the existing scripts to make a new ciab-cn2, ciab-cn3..... ? Preferably with latest and greatest Ubuntu.

**Comment by kimusan** [comment]
Did try to Google but have not found any solutions that work. It tells me that the window manager quits right away.

21.04 was the one do-release-update selected

**Comment by bmullan** [comment]
I'd just wait for the first point release for 22.04.1 LTS   should be in
August

**Comment by bmullan** [comment]
Until the 22.04.1 is released the only way to get there is to
do-release-upgrade to 21.10, reboot
Then do-release-upgrade again to 22.04 LTS.

Be aware there is one bug regarding a Ubuntu module called apart which
cause the desktop install to fail... But there is a simple 3 cmd workaround.

But one I haven't figured out yet is audio.

I ubuntu 22.04 installs both Pipewire & Pulseaudio.  One for video & one
for Audio.

I don't know if Pulseaudio build is broken or if Pipewire is handling audio
I may not know how to configure it well enough yet.

**Comment by bmullan** [comment]
That big in 22.04 is with the avoid module

CMD="sudo apt-get install -y acpid"

lxc exec ${CN_NAME} -- $CMD

# below is one line
CMD="systemctl disable --now acpid.service  acpid.socket acpid.path"

lxc exec ${CN_NAME} -- $CMD

**Comment by bmullan** [comment]
Also read thru c-energys article:
**http://c-nergy.be/blog/?p=16682**

I'm using a newer version of their script than used in the installation on Ubuntu 20.04

**Comment by bmullan** [comment]
Re
> I guess I can get around this problem completely by adding the lines you mentioned.

That's what I did.  I put those 3 lines into my script...  Just before I do *lxc launch* of the container.

**Comment by bmullan** [comment]
Kim
After weeks w
working  to get CIAB working with Ubuntu 22.04... today I finally got
Pipewire working with xRDP so audio worked.
I think I must be one of the first to do so because all I've seen in
forums, Reddit etc is:

xRDP does not work with Pipewire 🤗

Brian

**Comment by bmullan** [comment]
*kim read this secttion*
this section:
*https://c-nergy.be/blog/?p=16817&cpage=1#comments
<https://c-nergy.be/blog/?p=16817&cpage=1#comments>*

this section:

Black Screen or disconnected immediately after connecting

As mentioned and explained multiple times,  this situation will happen (or
can happen) when the same user account is used concurrently locally and
remotely.  In other words,  the problem is related to the fact that the* same
user account* is already logged in locally and a remote connection is
attempted at the same time.  With xRDP software solution, a specific user
account can be logged on either* locally or remotely* but not both….

You can read more information and some workarounds (provided as is) to try
to fix the issues in the following posts

   - xRDP – xRDP shows only black screen after authentication windows –
   HowTo Fix ! <https://c-nergy.be/blog/?p=16682>
   - xRDP – Allow multiple sessions (local and remote) for the same user –
   HowTo <https://c-nergy.be/blog/?p=16698>

Black Screen or disconnected immediately after connecting

As mentioned and explained multiple times,  this situation will happen (or
can happen) when the same user account is used concurrently locally and
remotely.  In other words,  the problem is related to the fact that the* same
user account* is already logged in locally and a remote connection is
attempted at the same time.  With xRDP software solution, a specific user
account can be logged on either* locally or remotely* but not both….

You can read more information and some workarounds (provided as is) to try
to fix the issues in the following posts

   - xRDP – xRDP shows only black screen after authentication windows –
   HowTo Fix ! <https://c-nergy.be/blog/?p=16682>
   - xRDP – Allow multiple sessions (local and remote) for the same user –
   HowTo <https://c-nergy.be/blog/?p=16698>

**Comment by kimusan** [comment]
Like I wrote, I got that fixed, got multiple desktops, including ubuntu 22.04 running with sound and no black screen.
